FROM postgres:15.0-alpine

LABEL version="15.0-alpine" description="postgres 15.0 alpine" maintainer="Esdras Schonevald<esdraschonevald@gmail.com>"

ENV POSTGRES_DB petweb
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres