version: '3'

services:

  postgres:
    container_name: postgres
    image: postgres:${POSTGRES_VERSION}
    restart: always
    ports:
      - ${POSTGRES_LOCAL_PORT}:${POSTGRES_REMOTE_PORT}
    volumes:
      - ${POSTGRES_VOLUME_PATH}:/var/lib/postgresql/data

  php:
    container_name: php
    build: ./.docker/php
    restart: always
    expose:
      - ${PHP_FPM_PORT}
    volumes:
      - ${APPLICATION_ROOT}:/var/www
    depends_on:
      - postgres

  composer:
    container_name: composer
    image: composer:latest
    volumes:
      - ${APPLICATION_ROOT}:/composer
    working_dir: /composer
    command: install

  nginx:
    container_name: nginx
    image: nginx:${NGINX_VERSION}
    restart: always
    ports:
      - "${APPLICATION_PORT}:80"
    volumes:
      - ${APPLICATION_ROOT}:/var/www
      - ${NGINX_CONF_PATH}:/etc/nginx/conf.d
    depends_on:
      - php