version: '3'

services:

  petweb_api_postgres:
    container_name: petweb_api_postgres
    image: ${POSTGRES_VERSION}
    restart: always
    ports:
      - ${POSTGRES_REMOTE_PORT}
    volumes:
      - ${POSTGRES_VOLUME_PATH}:/var/lib/postgresql/data
    env_file:
      - .env

  petweb_api_php:
    container_name: petweb_api_php
    image: ${PHP_VERSION}
    restart: always
    expose:
      - ${PHP_FPM_PORT}
    volumes:
      - ${APPLICATION_ROOT}:/var/www
    depends_on:
      - petweb_api_postgres
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  petweb_api_composer:
    container_name: petweb_api_composer
    image: composer:latest
    volumes:
      - ${APPLICATION_ROOT}:/composer
    working_dir: /composer
    command: install

  petweb_api_nginx:
    container_name: petweb_api_nginx
    image: ${NGINX_VERSION}
    restart: always
    ports:
      - "${APPLICATION_PORT}:80"
    volumes:
      - ${APPLICATION_ROOT}:/var/www
      - ${NGINX_CONF_PATH}:/etc/nginx/conf.d
    depends_on:
      - petweb_api_php