controllers:
  resource: ../src/Controller/
  type: attribute

dia_semana_find:
  path: api/semana/dias/{id}
  methods: ["GET"]
  defaults:
    _controller: Petweb\Api\Controller\DiaSemanaController::find
    _api_resource_class: Petweb\Api\Entity\DiaSemana
    _api_item_operation_name: dia_semana

dia_semana_find_all:
  path: api/semana/dias
  methods: ["GET"]
  defaults:
    _controller: Petweb\Api\Controller\DiaSemanaController::findAll
    _api_resource_class: Petweb\Api\Entity\DiaSemana
    _api_item_operation_name: dia_semana
