name: Deploy to Amazon ECS

on:
  push:
    branches: 
      - master

permissions: write-all

env:
  AWS_REGION: us-east-2                       # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: ec2-3-144-212-85            # set this to your Amazon ECR repository name

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
        aws-region: ${{ env.AWS_REGION }}

    #- name: Prepare SSH
    #  run: >
    #    su && apt-get -yq update && \
    #    apt-get -yq install ssh
        
    - name: Add IP to known hosts
      run: mkdir ~/.ssh && echo "${{ secrets.SSH_HOSTKEY }}" >> ~/.ssh/known_hosts

    - name: Deploy
      run: >
        rsync /home/runner/work/petweb-api/petweb-api/ \
        ec2-user@ec2-3-144-212-85.us-east-2.compute.amazonaws.com:/var/www/petweb \
        --rsh "ssh -p 22 -i /home/runner/.ssh/deploy_key -o StrictHostKeyChecking=yes" \
        --recursive
        
    #  uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        ARGS: "-rltgoDzvO --delete"
        SOURCE: "./"
        REMOTE_HOST: "ec2-3-144-212-85.us-east-2.compute.amazonaws.com"
        REMOTE_USER: "ec2-user"
        TARGET: "/var/www/petweb"
