name: Deploy to Amazon ECS

on:
  push:
    branches: "master"

permissions:
  contents: write

env:
  AWS_REGION: us-east-2                       # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: ec2-3-144-212-85            # set this to your Amazon ECR repository name


jobs:
  build:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v3
          
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        SOURCE: .
        REMOTE_HOST: ec2-3-144-212-85.us-east-2.compute.amazonaws.com
        REMOTE_USER: ec2-user
        TARGET: /var/www/petweb
        EXCLUDE: "/dist/, /node_modules/, /vendor/, .github/, .git/, **.env"
